export interface Feature {
    icon: string;
    title: string;
    desc: string;
    href: string;
}

export const features: Feature[] = [
    { icon: "⏱️", title: "Radni sati", desc: "Evidencija dolaska i odlaska, pauze, prekovremeni. Radnici unose sate s mobitela, admin odobrava jednim klikom.", href: "/radni-sati" },
    { icon: "📂", title: "Projekti", desc: "Praćenje statusa, dodjela radnika, budžet i troškovi. Sve na jednom mjestu, u realnom vremenu.", href: "/projekti" },
    { icon: "📋", title: "Računi", desc: "Unos i pregled računa, fotografije, odobravanje troškova. Potpuna kontrola financija.", href: "/racuni" },
    { icon: "📦", title: "Otpremnice", desc: "Digitalni otpremni list s potpisom, fotografijom i automatskim obračunom. Kraj papirnatologije.", href: "/otpremnice" },
    { icon: "🚗", title: "Vozila", desc: "Evidencija službenih vozila, registracije, servisi, prijeđeni kilometri. Sve na jednom mjestu.", href: "/vozila" },
    { icon: "👷", title: "Panel za radnike", desc: "Svaki radnik ima svoj profil — unos sati, pregled projekata, obavijesti i osobni pregled evidencije.", href: "/panel-za-radnike" },
    { icon: "🏠", title: "Smještaj", desc: "Upravljanje smještajem radnika na terenu. Kapaciteti, raspored, troškovi i lokacije.", href: "/smjestaj" },
    { icon: "✅", title: "Obaveze", desc: "Praćenje zadataka i obaveza po projektu i radniku. Rokovi, prioriteti, status.", href: "/obaveze" },
    { icon: "📊", title: "Izvještaji & Analize", desc: "Detaljni izvještaji po radniku, projektu, periodu. PDF export, CSV download, grafički prikazi.", href: "/izvjestaji" },
    { icon: "🔒", title: "Sigurnost", desc: "SHA-256 enkripcija PIN-ova, rate limiting, audit log svakog pokreta. Vaši podaci su sigurni.", href: "/sigurnost" },
    { icon: "📋", title: "Dnevnik radova", desc: "Digitalni građevinski dnevnik — opis radova, materijali, oprema, fotografije. Automatsko povlačenje prognoze.", href: "/dnevnik" },
    { icon: "☀️", title: "Vrijeme", desc: "Vremenska prognoza za svako gradilište. Upozorenja za nepogode, praćenje utjecaja na produktivnost.", href: "/vrijeme" },
    { icon: "📡", title: "GPS Nadzor", desc: "Praćenje lokacije radnika u realnom vremenu. Geofence zone, upozorenja, karta gradilišta.", href: "/gps-nadzor" },
    { icon: "📷", title: "QR Check-in", desc: "Dolazak i odlazak skeniranjem QR koda na gradilištu. GPS verifikacija, automatski unos sati.", href: "/qr-checkin" },
    { icon: "🏖️", title: "GO & Odsutnosti", desc: "Godišnji odmori, bolovanja, slobodni dani. Zahtjevi, odobrenja, kalendar odsutnosti.", href: "/odmori" },
    { icon: "📅", title: "Kalendar", desc: "Pregled rasporeda, rokova i događaja. Mjesečni i tjedni prikaz s oznakama projekata i odmora.", href: "/kalendar" },
    { icon: "🔔", title: "Obavijesti", desc: "Push notifikacije za odobrenja, rokove, zadatke. Radnici i admin uvijek informirani.", href: "/obavijesti" },
];

export const subpageData: Record<string, {
    icon: string; title: string; heroTitle: string; heroHighlight: string;
    subtitle: string; howTitle: string; howDesc: string;
    checks: string[]; benefits: { icon: string; title: string; desc: string }[];
    ctaTitle: string; ctaDesc: string;
}> = {
    "radni-sati": { icon: "⏱️", title: "Radni sati", heroTitle: "Svaki sat", heroHighlight: "evidentiran. Precizno.", subtitle: "Radnici unose sate s mobitela, admin odobrava jednim klikom. Dolazak, odlazak, pauze, prekovremeni — sve na jednom mjestu.", howTitle: "Unesi, odobri, izvezi — tri koraka do reda", howDesc: "Radnik odabere projekt, unese vrijeme dolaska i odlaska. Admin pregleda, odobri ili vrati na ispravak. Odobreni sati idu u izvještaje i obračun.", checks: ["Unos sati s mobitela ili desktopa", "Dolazak, odlazak, pauza, prekovremeni", "Odobravanje jednim klikom", "Filtriranje po projektu, radniku, datumu", "PDF i Excel export", "Automatski obračun ukupnih sati"], benefits: [{ icon: "📱", title: "S mobitela", desc: "Radnik unese sate odmah na terenu." }, { icon: "✅", title: "Odobrenje", desc: "Admin odobrava ili vraća — transparentno." }, { icon: "📊", title: "Izvještaji", desc: "Automatski izvještaji po radniku i projektu." }], ctaTitle: "Precizna evidencija\nradnog vremena?", ctaDesc: "Isprobaj besplatno i digitaliziraj evidenciju sati." },
    "projekti": { icon: "📂", title: "Projekti", heroTitle: "Projekti pod", heroHighlight: "punom kontrolom.", subtitle: "Status, budžet, radnici, rokovi. Sve informacije o svakom projektu na jednom mjestu, ažurirane u realnom vremenu.", howTitle: "Kreiraj projekt, dodijeli radnike, prati napredak", howDesc: "Admin kreira projekt s lokacijom, budžetom i rokovima. Dodjeljuje radnike i voditelje. Sustav prati troškove, sate i status u realnom vremenu.", checks: ["Kreiranje projekta s lokacijom i budžetom", "Dodjela radnika i voditelja", "Praćenje troškova u realnom vremenu", "Status projekta (aktivan, pauziran, završen)", "GPS koordinate gradilišta", "Integracija sa svim modulima"], benefits: [{ icon: "📍", title: "Lokacija", desc: "GPS koordinate za svako gradilište." }, { icon: "💰", title: "Budžet", desc: "Praćenje troškova vs. planirani budžet." }, { icon: "👥", title: "Tim", desc: "Tko radi na kojem projektu — uvijek jasno." }], ctaTitle: "Potpuna kontrola\nnad projektima?", ctaDesc: "Isprobaj besplatno i upravljaj projektima profesionalno." },
    "racuni": { icon: "📋", title: "Računi", heroTitle: "Računi R1", heroHighlight: "digitalno. Uredno.", subtitle: "Unos računa, fotografije dokumenata, odobravanje troškova. Potpuna kontrola financija bez papira.", howTitle: "Fotografiraj, unesi, odobri — kraj papirnatologije", howDesc: "Radnik fotografira račun na terenu, admin pregleda i odobrava. Sustav čuva sve digitalno s mogućnošću pretrage i izvoza.", checks: ["Unos računa s fotografijom", "Odobravanje troškova", "Filtriranje po projektu i periodu", "PDF export", "Kategorije troškova", "Pregled ukupnih izdataka"], benefits: [{ icon: "📸", title: "Foto dokaz", desc: "Svaki račun ima fotografiju originala." }, { icon: "🔍", title: "Pretraga", desc: "Pronađi bilo koji račun u sekundi." }, { icon: "📄", title: "PDF Export", desc: "Izvezi sve račune u PDF format." }], ctaTitle: "Digitalni računi\nbez papira?", ctaDesc: "Isprobaj besplatno i digitaliziraj sve račune." },
    "otpremnice": { icon: "📦", title: "Otpremnice", heroTitle: "Otpremnice", heroHighlight: "bez papira.", subtitle: "Digitalni otpremni list s potpisom na ekranu, fotografijom robe i automatskim obračunom.", howTitle: "Fotografiraj robu, potpiši, pošalji — gotovo", howDesc: "Radnik fotografira robu, unese detalje, klijent potpisuje na ekranu. PDF se generira automatski.", checks: ["Digitalni potpis na ekranu", "Fotografija robe", "Automatski PDF", "Pregled po projektu", "Status otpremnice", "Export i slanje putem emaila"], benefits: [{ icon: "✍️", title: "E-potpis", desc: "Klijent potpisuje na ekranu mobitela." }, { icon: "📸", title: "Foto robe", desc: "Dokumentiraj svaku isporuku fotografijom." }, { icon: "⚡", title: "Auto-PDF", desc: "PDF nastane automatski — zero effort." }], ctaTitle: "Digitalne otpremnice\nza gradilište?", ctaDesc: "Isprobaj besplatno i ukini papirnate otpremne listove." },
    "vozila": { icon: "🚗", title: "Vozila", heroTitle: "Fleet pod", heroHighlight: "kontrolom.", subtitle: "Evidencija službenih vozila, registracije, servisi, kilometri. Sve informacije na jednom mjestu.", howTitle: "Dodaj vozilo, evidentiraj kilometre, prati servise", howDesc: "Admin dodaje vozila s registracijskim podatcima. Sustav prati kilometre, servise i troškove.", checks: ["Evidencija vozila i registracija", "Praćenje kilometara", "Servisi i troškovi", "Dodjela vozila radnicima", "Upozorenja za isteke", "Izvještaji po vozilu"], benefits: [{ icon: "🔧", title: "Servisi", desc: "Nikad ne propusti servisni interval." }, { icon: "⛽", title: "Troškovi", desc: "Praćenje potrošnje goriva i održavanja." }, { icon: "📋", title: "Registracija", desc: "Upozorenje prije isteka registracije." }], ctaTitle: "Kontrola\nvoznog parka?", ctaDesc: "Isprobaj besplatno i upravljaj vozilima digitalno." },
    "panel-za-radnike": { icon: "👷", title: "Panel za radnike", heroTitle: "Radnički panel", heroHighlight: "za svakoga.", subtitle: "Svaki radnik ima svoj profil — unos sati, pregled projekata, obavijesti i osobni pregled evidencije.", howTitle: "Prijava, pregled, unos — sve u jednoj aplikaciji", howDesc: "Radnik se prijavi PIN-om, vidi svoje projekte, unese sate i prati obavijesti. Jednostavno i brzo.", checks: ["Osobni dashboard za radnika", "Unos radnih sati", "Pregled projekata", "Obavijesti i zadaci", "Kalendar odsutnosti", "QR check-in pristup"], benefits: [{ icon: "🔐", title: "Siguran PIN", desc: "SHA-256 enkriptirani PIN za prijavu." }, { icon: "📱", title: "Mobilno", desc: "Optimizirano za mobitel — radi na terenu." }, { icon: "👁️", title: "Transparentno", desc: "Radnik vidi sve svoje podatke." }], ctaTitle: "Panel za\nsvakoga radnika?", ctaDesc: "Isprobaj besplatno i daj radnicima pristup." },
    "smjestaj": { icon: "🏠", title: "Smještaj", heroTitle: "Smještaj radnika", heroHighlight: "organizirano.", subtitle: "Upravljanje smještajem radnika na terenu. Kapaciteti, raspored, troškovi i lokacije.", howTitle: "Dodaj smještaj, rasporedi radnike, prati troškove", howDesc: "Admin dodaje objekte, definira kapacitete i raspoređuje radnike. Sustav prati zauzetost i troškove.", checks: ["Evidencija objekata i kapaciteta", "Raspored radnika po smještaju", "Praćenje troškova", "Lokacije na karti", "Zauzetost i dostupnost", "Izvještaji"], benefits: [{ icon: "🏠", title: "Kapaciteti", desc: "Vidi tko je gdje smješten i koliko ima mjesta." }, { icon: "💰", title: "Troškovi", desc: "Praćenje mjesečnih troškova smještaja." }, { icon: "📍", title: "Lokacije", desc: "Smještaj na karti — blizu gradilišta." }], ctaTitle: "Organizirani smještaj\nradnika?", ctaDesc: "Isprobaj besplatno i digitaliziraj upravljanje smještajem." },
    "obaveze": { icon: "✅", title: "Obaveze", heroTitle: "Obaveze i zadaci", heroHighlight: "bez propusta.", subtitle: "Praćenje zadataka i obaveza po projektu i radniku. Rokovi, prioriteti, status — ništa ne prolazi neopaženo.", howTitle: "Kreiraj zadatak, dodijeli, prati rok", howDesc: "Admin kreira obavezu, dodjeljuje radniku, postavlja rok. Sustav šalje reminder i prati status do završetka.", checks: ["Kreiranje zadataka s rokovima", "Dodjela po projektu i radniku", "Prioriteti (hitno, normalno, nisko)", "Status praćenje", "Automatski reminderi", "Pregled po timu"], benefits: [{ icon: "⏰", title: "Rokovi", desc: "Automatski reminderi prije isteka roka." }, { icon: "🎯", title: "Prioriteti", desc: "Hitno, normalno, nisko — uvijek jasno." }, { icon: "📋", title: "Pregled", desc: "Dashboard svih obaveza na jednom mjestu." }], ctaTitle: "Obaveze pod\nkontrolom?", ctaDesc: "Isprobaj besplatno i nikad ne propusti važan rok." },
    "izvjestaji": { icon: "📊", title: "Izvještaji & Analize", heroTitle: "Izvještaji koji", heroHighlight: "govore podatke.", subtitle: "Detaljni izvještaji po radniku, projektu, periodu. PDF export, CSV download, grafički prikazi.", howTitle: "Filtriraj, analiziraj, izvezi — podaci na dlanu", howDesc: "Odaberi period, projekt ili radnika. Sustav generira detaljan izvještaj s grafovima, tablicama i mogućnošću izvoza.", checks: ["Izvještaji po radniku i projektu", "PDF i Excel export", "Grafički prikazi i dijagrami", "Filtriranje po periodu", "Usporedba perioda", "Automatski mjesečni sažetak"], benefits: [{ icon: "📊", title: "Grafovi", desc: "Vizualni prikaz podataka za brzi uvid." }, { icon: "📄", title: "PDF Export", desc: "Profesionalni izvještaji jednim klikom." }, { icon: "🔄", title: "Usporedba", desc: "Usporedi mjesece, projekte, radnike." }], ctaTitle: "Profesionalni\nizvještaji?", ctaDesc: "Isprobaj besplatno i dobivaš izvještaje kakve zaslužuješ." },
    "sigurnost": { icon: "🔒", title: "Sigurnost", heroTitle: "Sigurnost na", heroHighlight: "prvom mjestu.", subtitle: "SHA-256 enkripcija, rate limiting, audit log svakog pokreta. Vaši podaci su zaštićeni.", howTitle: "Enkripcija, logovi, kontrola pristupa", howDesc: "Svaki PIN je SHA-256 enkriptiran. Svaka akcija se bilježi u audit log. Rate limiting štiti od brute-force napada.", checks: ["SHA-256 enkripcija PIN-ova", "Rate limiting za prijavu", "Audit log svih akcija", "Kontrola pristupa po ulozi", "Session timeout", "HTTPS enkripcija"], benefits: [{ icon: "🔐", title: "Enkripcija", desc: "Industrijski standard zaštite podataka." }, { icon: "📝", title: "Audit Log", desc: "Svaka akcija je zapisana i pretraživa." }, { icon: "🛡️", title: "Zaštita", desc: "Rate limiting i session kontrola." }], ctaTitle: "Sigurnost bez\nkompromisa?", ctaDesc: "Isprobaj besplatno — tvoji podaci su zaštićeni." },
    "dnevnik": { icon: "📋", title: "Dnevnik radova", heroTitle: "Građevinski dnevnik", heroHighlight: "uvijek pri ruci.", subtitle: "Svaki radni dan dokumentiran — opis radova, materijali, oprema, fotografije. Automatski povlači prognozu za lokaciju gradilišta.", howTitle: "Popuni, fotografiraj, potvrdi jednim klikom", howDesc: "Radnik otvori dnevni unos, odabere projekt, opiše radove, navede materijale i opremu. Vi-Di-Sef automatski povlači vremensku prognozu.", checks: ["Opis izvršenih radova po danu i projektu", "Evidencija materijala i opreme", "Automatska prognoza za gradilište", "Fotografije s terena — direktno s mobitela", "Filtriranje po projektu, datumu", "Sigurnosne bilješke"], benefits: [{ icon: "📸", title: "Foto dokumentacija", desc: "Fotografiraj radove izravno s mobitela." }, { icon: "🌡️", title: "Auto-vrijeme", desc: "Automatska prognoza za lokaciju." }, { icon: "🔍", title: "Pretraživo", desc: "Pretraži po opisu, materijalu, datumu." }], ctaTitle: "Digitalni\ngrađevinski dnevnik?", ctaDesc: "Isprobaj besplatno i dokumentiraj svaki radni dan." },
    "vrijeme": { icon: "☀️", title: "Vrijeme", heroTitle: "Vrijeme na gradilištu", heroHighlight: "u realnom vremenu.", subtitle: "Prognoza za svaki projekt — temperatura, oborine, vjetar. Upozorenja za nepogode, AI analiza produktivnosti.", howTitle: "Prognoza za svako gradilište, upozorenja za ekstreme", howDesc: "Vi-Di-Sef automatski dohvaća prognozu za GPS koordinate svakog projekta. AI analizira korelaciju vremena i produktivnosti.", checks: ["Trenutna temperatura i uvjeti po projektu", "7-dnevna i 16-dnevna prognoza", "Upozorenja za ekstremne uvjete", "AI analiza: vrijeme vs. produktivnost", "Pravila po aktivnostima", "Integracija s dnevnikom radova"], benefits: [{ icon: "⚡", title: "Planiraj unaprijed", desc: "Prilagodi raspored prema prognozi." }, { icon: "🧠", title: "AI uvidi", desc: "Analiza utjecaja vremena na produktivnost." }, { icon: "🔔", title: "Upozorenja", desc: "Push notifikacije za ekstremne uvjete." }], ctaTitle: "Planiraj radove\nprema vremenu?", ctaDesc: "Isprobaj besplatno i nikad više ne gubi dane." },
    "gps-nadzor": { icon: "📡", title: "GPS Nadzor", heroTitle: "Znaj gdje su ti", heroHighlight: "radnici. Uvijek.", subtitle: "Praćenje lokacije radnika u realnom vremenu na karti. Geofence zone, upozorenja, statistika prisutnosti.", howTitle: "Karta, geofence i upozorenja — potpuni nadzor", howDesc: "Svaki radnik dijeli lokaciju kad je na poslu. Admin vidi sve na karti. Geofence radijus detektira tko je u zoni.", checks: ["Karta s lokacijama radnika", "Geofence zone oko gradilišta", "Upozorenje kad radnik izađe iz zone", "Statistika: u zoni vs. izvan", "Privatnost — GPS samo za radno vrijeme", "Povijest lokacija"], benefits: [{ icon: "🗺️", title: "Karta uživo", desc: "Svi radnici na jednoj karti." }, { icon: "🚨", title: "Geofence", desc: "Upozorenje kad radnik izađe iz zone." }, { icon: "🔒", title: "Privatnost", desc: "GPS samo za radno vrijeme." }], ctaTitle: "Potpuni pregled\nlokacija radnika?", ctaDesc: "Isprobaj besplatno i znaj gdje su tvoji radnici." },
    "qr-checkin": { icon: "📷", title: "QR Check-in", heroTitle: "Skeniraj. Prijavi se.", heroHighlight: "Gotovo.", subtitle: "Radnik skenira QR kod na gradilištu i automatski se prijavljuje. GPS verifikacija, automatski unos sati.", howTitle: "QR kod na gradilištu, mobitel u ruci — to je sve", howDesc: "Admin generira QR kod za svaki projekt. Radnik skenira kamerom. Sustav bilježi dolazak s GPS lokacijom.", checks: ["Skeniranje QR koda kamerom", "GPS verifikacija lokacije", "Automatski unos radnih sati", "Ručni unos koda kao fallback", "Prikaz aktivnog check-ina", "Integracija s evidencijom sati"], benefits: [{ icon: "⚡", title: "2 sekunde", desc: "Dolazak evidentiran u 2 sekunde." }, { icon: "📍", title: "GPS dokaz", desc: "Svaki check-in sadrži GPS koordinate." }, { icon: "🔄", title: "Auto-evidencija", desc: "Sati se kreiraju iz check-in podataka." }], ctaTitle: "Evidencija dolaska\nbez papira?", ctaDesc: "Isprobaj besplatno i digitaliziraj prijavu." },
    "odmori": { icon: "🏖️", title: "GO & Odsutnosti", heroTitle: "Odmori i odsutnosti", heroHighlight: "pod kontrolom.", subtitle: "Radnici šalju zahtjeve za GO, bolovanje ili slobodan dan. Admin odobrava jednim klikom. Kalendar odsutnosti.", howTitle: "Zahtjev, odobrenje, kalendar — sve digitalno", howDesc: "Radnik podnosi zahtjev, admin dobije notifikaciju i odobri ili odbije. Sustav prati preostale dane.", checks: ["Zahtjevi za GO, bolovanje, slobodan dan", "Odobravanje jednim klikom", "Kalendar odsutnosti tima", "Praćenje preostalih dana", "Notifikacije za zahtjeve", "Pregled po radniku i tipu"], benefits: [{ icon: "📅", title: "Kalendar tima", desc: "Vidi tko je odsutan bilo koji dan." }, { icon: "⚡", title: "Brzo odobrenje", desc: "Zahtjev → odobrenje → notifikacija." }, { icon: "📊", title: "Statistika", desc: "Preostali dani GO, bolovanja." }], ctaTitle: "Upravljaj odmorima\nbez papira?", ctaDesc: "Isprobaj besplatno i digitaliziraj odsutnosti." },
    "kalendar": { icon: "📅", title: "Kalendar", heroTitle: "Sve na jednom", heroHighlight: "kalendaru.", subtitle: "Mjesečni i tjedni pregled — projekti, sati, odmori, obaveze. Vizualno jasno, s bojama po kategoriji.", howTitle: "Projekti, odmori, obaveze — sve na jednom mjestu", howDesc: "Kalendar prikazuje sve događaje iz sustava automatski. Prebacuj se između mjesečnog i tjednog prikaza.", checks: ["Mjesečni i tjedni prikaz", "Boje po kategoriji", "Automatski unos iz svih modula", "Dostupnost radnika po danu", "Rokovi obaveza s prioritetima", "Filtriranje po radniku i projektu"], benefits: [{ icon: "🎨", title: "Vizualno jasno", desc: "Boje po kategorijama — odmah vidiš." }, { icon: "🔗", title: "Auto-povezano", desc: "Puni se automatski iz svih modula." }, { icon: "👥", title: "Tim na dlanu", desc: "Dostupnost cijelog tima." }], ctaTitle: "Pregled cijelog tima\nna jednom kalendaru?", ctaDesc: "Isprobaj besplatno i nikad ne propusti rok." },
    "obavijesti": { icon: "🔔", title: "Obavijesti", heroTitle: "Uvijek u toku.", heroHighlight: "Nikad iznenađen.", subtitle: "Push notifikacije za odobrenja, rokove, zadatke. Admin i radnici dobivaju prave informacije u pravo vrijeme.", howTitle: "Prava obavijest, pravoj osobi, u pravo vrijeme", howDesc: "Vi-Di-Sef šalje push notifikacije za ključne događaje. Sve filtrirano po ulozi.", checks: ["Push notifikacije na mobitel i desktop", "Odobrenja sati, odmora, zahtjeva", "Upozorenja za isteke rokova", "Filtrirane po ulozi", "Centar obavijesti s poviješću", "Brze akcije iz obavijesti"], benefits: [{ icon: "⚡", title: "Instant", desc: "Push notifikacije stižu odmah." }, { icon: "🎯", title: "Relevantno", desc: "Svaka uloga vidi samo svoje." }, { icon: "✅", title: "Brze akcije", desc: "Odobri direktno iz obavijesti." }], ctaTitle: "Uvijek informiran,\nnikad iznenađen?", ctaDesc: "Isprobaj besplatno i aktiviraj push obavijesti." },
};
